apiVersion: apps/v1
kind: Deployment
metadata:
  name: css-deployment1
spec:
  replicas: 2
  selector:
    matchLabels:
        project: css-jenkins1
  template:
    metadata:
      name: css-pod
      labels:
        project: css-jenkins1  
    spec:
      containers:
      - name: css-pod
        image: public.ecr.aws/n4f2g6n0/css-template:latest
        ports:
        - containerPort: 80
          protocol: TCP  
