apiVersion: apps/v1
kind: Deployment
metadata:
  name: css-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
        project: css-jenkins
  template:
    metadata:
      name: css-pod
      labels:
        project: css-jenkins  
    spec:
      containers:
      - name: css-pod
        image: ubuntu
      
